name: Daily Token Check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Add manual run event

jobs:
  token_check:
    runs-on: ubuntu-latest
    env:
      G_TOKEN: ${{ secrets.G_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run token check
        run: python bad_token_remover.py

      - name: Set Git identity
        run: |
          git config --global user.email "everpadd4@gmail.com"
          git config --global user.name "thelime1"

      - name: Create new branch
        run: |
          git checkout -b new-branch
          git add .
          git commit -m "Remove bad tokens"

      - name: Create pull request
        env:
          ACCESS_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic ${{ secrets.G_TOKEN }}"
          git push origin new-branch --set-upstream
          gh pr create -b new-branch -t "Remove bad tokens"
